@startuml
title Диаграмма уровня кода

top to bottom direction

!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

class ChangeTemperatureRequest {}

class AuthMiddleware {}

class HeatingSystemController {}

class HeatingSystemRepository {}

class HeatingSystemTemperatureChangeRequestsQueue {}

ChangeTemperatureRequest --> AuthMiddleware : авторизация
AuthMiddleware --> HeatingSystemController : отправка запроса после прохождения авторизации
HeatingSystemController --> HeatingSystemRepository : сохранение данных о температуре в БД
HeatingSystemController --> HeatingSystemTemperatureChangeRequestsQueue : отправка запрошенных данных о температуре в систему

@enduml